parameters:
    ypt_jq_grid.twig_extension.class: NXC\SafeBundle\Twig\JqGridExtension

services:
  nxc.safe.admin.whisper:
    class: NXC\SafeBundle\Admin\WhisperAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: safe, label: whisper }
    arguments: [null, NXC\SafeBundle\Entity\Whisper, SonataAdminBundle:CRUD]
  nxc.safe.secured:
        class: NXC\SafeBundle\Secured\Manager
        arguments:
            container: "@service_container"
  ypt_jq_grid.twig.extension:
    class: %ypt_jq_grid.twig_extension.class%
    tags:
      - { name: twig.extension }
    arguments:
        container: "@router"

#    nxc_safe.example:
#        class: %nxc_safe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#
#    tt.safe.admin.whisper:
#          class: NXC\SafeBundle\Admin\WhisperAdmin
#          tags:
#            - { name: sonata.admin, manager_type: orm, group: safe, label: safe }
#          arguments: [null, NXC\SafeBundle\Admin\Entity\Whisper, SonataAdminBundle:CRUD]
