NXC\SafeBundle\Entity\Handshake:
    type: entity
    table: null
    repositoryClass: NXC\SafeBundle\Entity\HandshakeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        'string name':
            type: string
            length: 255
        value:
            type: string
            length: 255
    lifecycleCallbacks: {  }
