<?php

namespace NXC\SafeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SecuredController__JMSInjector
{
    public static function inject($container) {
        require_once 'Z:/home/symfony2/www/safe/app/cache/dev/jms_diextra/proxies/NXC-SafeBundle-Controller-SecuredController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('NXC\\SafeBundle\\Controller\\SecuredController' => array('helloadminAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_8a575de1a86785e1b2d48ab8bb58ad8f78a11998\__CG__\NXC\SafeBundle\Controller\SecuredController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
