<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use NXC\SafeBundle\Entity\Whisper;
/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    public function __construct() {
        parent::__construct();
        $this->whispers = new Doctrine\Common\Collections\ArrayCollection();
    }
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="Whisper", mappedBy="user")
     */
    protected $whispers;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    public function getWhispers() {
        return $this->whispers;
    }

    public function setWhispers(\NXC\SafeBundle\Entity\Whisper $whisper) {
        $this->whispers[] = $whisper;
    }


}