<?php

namespace NXC\SafeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HandshakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandshakeRepository extends EntityRepository
{
}
