<?php

namespace NXC\SafeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WhisperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhisperRepository extends EntityRepository {

    public function findAjaxValue($value) {
        $qb = $this->createQueryBuilder('w')->where('w.whisper like :title')->setParameter('title', '%' . $value . '%')->setMaxResults(10);
        ;

        return $qb->getQuery()->getResult();
    }

    public function getWhispersForUser($userId, $approved = true) {
        $qb = $this->createQueryBuilder('w')
                ->select('w')
                ->where('w.user = :user_id')
                ->addOrderBy('w.created')
                ->setParameter('user_id', $userId);

        if (false === is_null($approved))
            $qb->andWhere('w.approved = :approved')
                    ->setParameter('approved', $approved);

        return $qb->getQuery()
                        ->getResult();
    }

    public function getLatestWhispers($limit = 10) {
        $qb = $this->createQueryBuilder('w')
                ->select('w')
                ->addOrderBy('w.id', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                        ->getResult();
    }

}